# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/ct-web-lit"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@playwright/test"
  - package-ecosystem: "npm"
    directory: "/ct-web"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "@playwright/test"
  - package-ecosystem: "npm"
    directory: "/playwright-ct-web"
    schedule:
      interval: "daily"
